### ISSUE TITLE
Project 4

### ISSUE THREAD

**Issue by Bhooshan-s** [Bhooshan-s/Motioncut#4]
Here is a combined implementation for the College Time Table Management System:

### Project Structure

```
timetable-management/
├── backend/
│   ├── server.js
│   ├── models/
│   │   ├── user.js
│   │   └── schedule.js
├── frontend/
│   ├── index.html
│   ├── styles.css
│   └── scripts.js
├── package.json
└── package-lock.json
```

### Backend Implementation (Node.js and Express)

**server.js:**
```javascript
const express = require('express');
const mongoose = require('mongoose');
const bodyParser = require('body-parser');
const cors = require('cors');

const app = express();
app.use(bodyParser.json());
app.use(cors());

// Connect to MongoDB
mongoose.connect('mongodb://localhost/timetable', { useNewUrlParser: true, useUnifiedTopology: true });

// Import Models
const User = require('./models/user');
const Schedule = require('./models/schedule');

// Define Routes
app.post('/users', (req, res) => {
  const user = new User(req.body);
  user.save().then(user => res.send(user));
});

app.post('/schedules', (req, res) => {
  const schedule = new Schedule(req.body);
  schedule.save().then(schedule => res.send(schedule));
});

app.get('/schedules', (req, res) => {
  Schedule.find().then(schedules => res.send(schedules));
});

// Serve frontend
app.use(express.static('../frontend'));

// Start the server
app.listen(3000, () => {
  console.log('Server is running on port 3000');
});
```

**models/user.js:**
```javascript
const mongoose = require('mongoose');

const UserSchema = new mongoose.Schema({
  username: String,
  role: String,
});

module.exports = mongoose.model('User', UserSchema);
```

**models/schedule.js:**
```javascript
const mongoose = require('mongoose');

const ScheduleSchema = new mongoose.Schema({
  course: String,
  day: String,
  startTime: String,
  endTime: String,
  instructor: String,
  room: String,
});

module.exports = mongoose.model('Schedule', ScheduleSchema);
```

### Frontend Implementation (HTML, CSS, and JavaScript)

**index.html:**
```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Time Table Management</title>
  <link rel="stylesheet" href="styles.css">
</head>
<body>
  <div id="app">
    <h1>College Time Table Management</h1>
    <form id="schedule-form">
      <input type="text" id="course" placeholder="Course" required>
      <input type="text" id="day" placeholder="Day" required>
      <input type="time" id="start-time" required>
      <input type="time" id="end-time" required>
      <input type="text" id="instructor" placeholder="Instructor" required>
      <input type="text" id="room" placeholder="Room" required>
      <button type="submit">Add Schedule</button>
    </form>
    <div id="schedule-list"></div>
  </div>
  <script src="scripts.js"></script>
</body>
</html>
```

**styles.css:**
```css
body {
  font-family: Arial, sans-serif;
  margin: 0;
  padding: 0;
  background-color: #f4f4f4;
}

#app {
  max-width: 600px;
  margin: 50px auto;
  padding: 20px;
  background: #fff;
  box-shadow: 0 0 10px rgba(0,0,0,0.1);
}

h1 {
  text-align: center;
  color: #333;
}

form {
  display: flex;
  flex-direction: column;
}

input {
  margin-bottom: 10px;
  padding: 10px;
  font-size: 16px;
}

button {
  padding: 10px;
  background: #007bff;
  color: white;
  border: none;
  cursor: pointer;
}

button:hover {
  background: #0056b3;
}

#schedule-list {
  margin-top: 20px;
}
```

**scripts.js:**
```javascript
document.getElementById('schedule-form').addEventListener('submit', async (event) => {
  event.preventDefault();
  const course = document.getElementById('course').value;
  const day = document.getElementById('day').value;
  const startTime = document.getElementById('start-time').value;
  const endTime = document.getElementById('end-time').value;
  const instructor = document.getElementById('instructor').value;
  const room = document.getElementById('room').value;

  const response = await fetch('http://localhost:3000/schedules', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({ course, day, startTime, endTime, instructor, room }),
  });

  const schedule = await response.json();
  displaySchedule(schedule);
});

async function loadSchedules() {
  const response = await fetch('http://localhost:3000/schedules');
  const schedules = await response.json();
  schedules.forEach(schedule => displaySchedule(schedule));
}

function displaySchedule(schedule) {
  const scheduleList = document.getElementById('schedule-list');
  const div = document.createElement('div');
  div.innerHTML = `
    <p>${schedule.course} - ${schedule.day} - ${schedule.startTime} - ${schedule.endTime} - ${schedule.instructor} - ${schedule.room}</p>
  `;
  scheduleList.appendChild(div);
}

window.onload = loadSchedules;
```

### Running the Application

1. **Start MongoDB**:
   Ensure MongoDB is running on your local machine.

2. **Install Dependencies**:
   ```bash
   npm install
   ```

3. **Run the Backend Server**:
   ```bash
   node backend/server.js
   ```

4. **Open the Frontend**:
   Open `frontend/index.html` in your web browser.

This combined implementation sets up the backend server with Express, connects to a MongoDB database, and provides a basic frontend interface for creating and displaying schedules. For a full-featured application, you can extend this example by adding more features and enhancements.
